# Generated by Django 5.1.5 on 2025-01-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(default='user', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
